<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Calculator_Test_Suit</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b1cfc86c-46d8-4e5c-a96e-761726de9978</testSuiteGuid>
   <testCaseLink>
      <guid>c0a67974-608c-4fa0-9271-7214a1220fa8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Add_Item_TestCase/Add_Kitchen_Office_Items</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>594f4440-67a0-4439-be3e-d15435d3fbc4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Add_Item_TestCase/Add_Custom_Item</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>530268cc-0278-4f06-98fc-39e055beadef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d581d271-c32a-4f5e-9bc0-f32715babadf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54ac7c05-4d54-4a4a-a1ba-1bf7069facc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69dcdc0c-4e86-4d45-834a-b8a48705a30f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
